DROP TABLE IF EXISTS TBL_OWNERS;
 
CREATE TABLE TBL_OWNERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  phone_number VARCHAR(15) DEFAULT NULL
);